services:
  web:
    image: nginx:latest
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      - laravel-development
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    env_file:
      - ./src/.env
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www
    networks:
      - laravel-development
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data-development:/var/lib/postgresql/data
    networks:
      - laravel-development

networks:
  laravel-development:

volumes:
  postgres-data-development:
